# Generated by Django 4.2 on 2023-05-09 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movimentacoes.categoriareceitas', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='pagador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contatos.contato', verbose_name='Pagador'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='valor',
            field=models.FloatField(max_length=255, verbose_name='Valor'),
        ),
    ]
