# Generated by Django 4.2 on 2023-05-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppImgs',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
