# Generated by Django 4.2.1 on 2023-05-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeCompras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListasDeCompras',
            new_name='ListaDeCompras',
        ),
    ]
