# Generated by Django 4.2 on 2023-05-08 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contatos', '0001_initial'),
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanejamentoCategoriaDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoCategoriaReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoSubcategoriaDespesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoSubcategoriaReceitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoRelacaoReceitaSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.receita')),
                ('id_subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.subcategoriareceitas')),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoRelacaoDespesaSubcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('id_despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.despesa')),
                ('id_subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimentacoes.subcategoriadespesas')),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.FloatField(max_length=255)),
                ('data', models.DateTimeField()),
                ('criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movimentacoes.categoriareceitas')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.contato')),
            ],
        ),
        migrations.CreateModel(
            name='PlanejamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_despesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movimentacoes.subcategoriadespesas')),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.contato')),
            ],
        ),
    ]
